com = g++
srcf = src
binf = build
hdf = include #headers folder
app = musicman

obj = 

aopt = -Wall #application compilation options

$(app): $(binf)/$(obj) $(srcf)/main.cpp
	$(com) $(aopt) $(obj) $(srcf)/main.cpp -o $(app)
